### ISSUE TITLE
Dimension table: List of columns extracted from the `identifierTemplate`.

### ISSUE THREAD

**Issue by tpluscode** [zazuko/data-cube-curation#141]
[...] it would be great if, for each `Table`, I could the list of columns extracted from the `identifierTemplate`.

_Originally posted by @martinmaillard in https://github.com/zazuko/data-cube-curation/pull/134#issuecomment-563262936_

**Comment by tpluscode** [comment]
@martinmaillard for a moment I thought about alternative data model design for this but in the end I think it only makes sense to add a new property to the dimension table

```
</table>
  dataCube:identifierTemplate "/{station-name}/{station-location}" ;
  dataCube:source </table-source> ;
  dataCube:identifierColumn 
    </table-source/column/station-name> ,
    </table-source/column/station-location> .
```

**Comment by martinmaillard** [comment]
Yeah I think that's enough :)
