### ISSUE TITLE
basic datatype support

### ISSUE THREAD

**Issue by tpluscode** [zazuko/data-cube-curation#145]
## Description

TBD

**Comment by tpluscode** [comment]
@ktk Please edit the issue with your requirements. We'll refine from there

**Comment by ktk** [comment]
We should IMO start with built-in-terms defined by the [CSVW spec](https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#built-in-datatypes)

From that list, I would propose to do autocomplete on the following types for the moment:
* number (xsd:double)
* datetime (xsd:dateTime)

for dateime we need to support a format specification, see [here](https://www.w3.org/TR/tabular-data-primer/#date-format) in the spec. This is definitely important as more often than not the format will be something else than ISO 8601.

I'm a bit confused why they only have dateTime as base datatype, in a lot of data the time is not important so we need to have xsd:date support as well.

In general it should be possible to select one of the CSVW datatypes we support out of the box or specify a full URI (or later a prefixed datatype) using autocompletion to our prefix.zazuko.com service.

**Comment by martinmaillard** [comment]
Summary of what I understand:
- The type field can contain any value (i.e. users can enter any URL)
- We offer auto-complete with a list of known types (string, number, datetime, etc)
- Some of the types have parameters (string -> language, datetime -> format, etc.) (Not sure how to handle that in the API @tpluscode )

**Comment by martinmaillard** [comment]
A possible implementation would be to accept any valid CSVW datatype in the API, and let the frontend construct these.

According to https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#cell-datatype, a valid datatype is:
- A valid built-in datatype string (https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#built-in-datatypes)
- A datatype description JSON object (https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#dfn-datatype-description)

**Comment by tpluscode** [comment]
I'm not sure I want to so closely match the CSVW description of the datatype specification. I propose to 

1. expand the current `dataCube:datatype` property to accept both a URI and a Literal
1. add an optional bag for the optional parameters

Examples follow. JSON-LD, but can be any RDF.
So, to use a custom property URI send:

```json
{
  "dataCube:datatype": { "@id": "schema:identifier" }
}
```

Any other property would also be sent as the full URI, and not CSVW shorthands.

```json
{
  "dataCube:datatype": { "@id": "xsd:date" },
  "dataCube:datatype/parameters": {
    "dataCube:datatype/format": "YYYY/MM/DD",
    "dataCube:datatype/minInclusive": "2000/01/01",
    "dataCube:datatype/default": "2010/06/23"
  }
}
```

As you see, I minted our local terms for the datatype specification. They closely resemble the ones in CSVW spec but will be less awkward if we want to deviate from it, or target other mapping format.

----

I think the API should mostly accept the above as-is and then convert (or fail) to produce the CSVW mapping document according to its requirements.

**Comment by tpluscode** [comment]
> I'm a bit confused why they only have dateTime as base datatype, in a lot of data the time is not important so we need to have xsd:date support as well.

@ktk it does support different dates. Check examples in para [6.4.4](https://www.w3.org/TR/2015/REC-tabular-data-model-20151217/#formats-for-dates-and-times)

**Comment by ktk** [comment]
@tpluscode yes that I know but there is no  built-in datatype called `date`, at least I don't see it.

**Comment by ktk** [comment]
@tpluscode I don't really care how CSVW calls it as long as we get `xsd:date` and `xsd:dateTime` options in the RDF output. I mean I don't want that it would cast a date into a dateTime.

**Comment by tpluscode** [comment]
> there is no built-in datatype called date, at least I don't see it.

From paragraph 5.11.1

> The possible built-in datatypes, as shown on the diagram, are:
> - the datatypes defined in [xmlschema11-2] as derived from and including anyAtomicType, whose identifier URLs are generated by prefixing the name with http://www.w3.org/2001/XMLSchema#

I understand this as "remove the xsd prefix and what remains it a valid built-in type". As long as it's derived from `anyAtomicType`

**Comment by ktk** [comment]
Ah interesting, thanks!

**Comment by martinmaillard** [comment]
> ```json
> {
>   "dataCube:datatype": { "@id": "schema:identifier" }
> }
> ```
> ...
> ```json
> {
>   "dataCube:datatype": { "@id": "xsd:date" },
>   "dataCube:datatype/parameters": {
>     "dataCube:datatype/format": "YYYY/MM/DD",
>     "dataCube:datatype/minInclusive": "2000/01/01",
>     "dataCube:datatype/default": "2010/06/23"
>   }
> }
> ```

That works for me! I'll only send valid CSVW datatypes at first, but we are not (too) tied to CSVW.

As for the parameters, I'll probably only support a subset of them for now. Supporting all of them requires a bit more UX research. I don't want a screen with 100 fields for each attribute 😆
