### ISSUE TITLE
Apply base URI to mapped properties

### ISSUE THREAD

**Issue by tpluscode** [zazuko/data-cube-curation#160]
- If I create new attributes with a bare name (not a URI), they still end up like `"csvw:propertyUrl": "http://localhost:5678/my-property"` in the mapping. We should probably use `baseUri` here?

_Originally posted by @martinmaillard in https://github.com/zazuko/data-cube-curation/pull/151#issuecomment-572498213_

**Comment by ktk** [comment]
It should be possible to set the baseUri per project IMO

**Comment by martinmaillard** [comment]
We already have per-project baseUri, but I just noticed it hasen't beed deployed yet. Will deploy a new version today (I just need to check with @tpluscode if it requires any data migrations).

**Comment by martinmaillard** [comment]
Closed by #173
