### ISSUE TITLE
Language tags not shown in preview (Table & Turtle)

### ISSUE THREAD

**Issue by ktk** [zazuko/data-cube-curation#162]
## Current behavior

In the preview language tagging seems to be ignored, both for Table and RDF Preview

## Expected behavior

Language tags should be shown.

**Comment by tpluscode** [comment]
Will be fixed when 5a4221b7760af944ae47a5ad89e50f8bd2997d79 is merged

**Comment by martinmaillard** [comment]
@tpluscode in the current version, it seems like the language is ignored altogether by the API when creating attributes.
