### ISSUE TITLE
UI: Safari issue with "RDF property input"

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/data-cube-curation#170]
Some special inputs don't seem to work on Safari. Needs investigation.

The most important issue we noticed is with the RDF property input. The dropdown doesn't show up, neither does the full URL below the input field.

**Comment by martinmaillard** [comment]
@tpluscode I just checked with Safari and don't have any issue. Is it still happening for you?

**Comment by tpluscode** [comment]
Seems to be working now. I updated to macOS Catalina in the meantime, so possibly it affects Safari <13?

**Comment by martinmaillard** [comment]
That sounds unlikely... no idea

Anyway, let's close this.
