### ISSUE TITLE
Unable to display the mapping from the fact table

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/data-cube-curation#203]
Project: https://datacube.zazukoians.org/app/projects/https:%2F%2Fdatacube.zazukoians.org%2Fproject%2F8f3a68e5-c545-4129-bf87-ec6f4b7fe3eb/tables

## Current behavior
Click on "View mapping" or "View mapped data" result in the message : "Error: Could not load mapping"

## Expected behavior
Should display the mapping or the mapped data, or give a more precise message about a missing field or other error. Previews in the dimension tables are ok.

**Comment by PDumasBAR** [comment]
Je ne peux afficher ni le mapping, ni les données de la table de fait. ça ne fonctionne que si je ne fais pas de lien avec une table de dimension. 

J'ai recré le projet depuis le début avec le même résultat : 
https://datacube.zazukoians.org/app/projects/https:%2F%2Fdatacube.zazukoians.org%2Fproject%2F9be16a02-6a5e-4264-85a3-26db1048220b/tables

Est-ce qu'il a un problème dans mes données ou mon mapping ?

**Comment by martinmaillard** [comment]
We are in the process of fixing this issue. A new version should be deployed soon.

(I'm keeping it in english so that my colleagues understand. I hope that's ok for you.)
