### ISSUE TITLE
Role de "Identifier attribute template"

### ISSUE THREAD

**Issue by cochardjl** [zazuko/data-cube-curation#207]
Lorsque je crée une Dimension table (projet SR1-fin), table Dim1, l'application propose un Identifier attribute template : "dim1/{_}".

Je ne comprends pas à quoi sert ce paramètre et si je ne le change pas, j'ai une erreur (zone en rouge) sans indication de ce que je dois faire.

=> documentation sur ce champ à améliorer.

**Comment by martinmaillard** [comment]
Translation:

> When I create a Dimension table (project SR1-fin) "table Dim1", the app provides an Identifier attribute template "dim/{_}".
>
> I don't understand what this parameter is for and if I don't change it, I get an error (red outline on the input) without any indication of what I should do.
>
> => improve documentation on this field.

I'm currently working on improving the error message. We will have to think about how we can make the purpose of the field easier to understand.

But basically, it defines how the identifier (URI) for each line of the input CSV file will be generated. So if we input for example `http://my-project.com/station/{station_id}`, it will use the `station_id` column to generate identifiers that look like the following:
```
http://my-project.com/station/1
http://my-project.com/station/2
http://my-project.com/station/3
http://my-project.com/station/4
```

If the value doesn't start with "http", (e.g. `station/{station_id}`) it will use the project's "base URI" to generate identifiers: `<project base URI>station/{station_id}`.
