### ISSUE TITLE
Handle different kinds of input files intelligently

### ISSUE THREAD

**Issue by tpluscode** [zazuko/data-cube-curation#21]
## Current

The API assumes that an uploaded source file is separated by semicolons and fails miserably whenever it happens to be actual comma-separated file.

## Expected

The API should at least recognize the comma vs semicolon and parse the file accordingly.

## Requirements

* The information on the file's format must be persisted along the state 
* In the resulting CSVW metadata file a `dialect` section should be generated including the determined delimiter

**Comment by martinmaillard** [comment]
@tpluscode that's done right?

**Comment by tpluscode** [comment]
Probably should do a thorough check some time, but the minimal setup is done
