### ISSUE TITLE
preview mapped data returns error "e is null"

### ISSUE THREAD

**Issue by Rdataflow** [zazuko/data-cube-curation#224]
## Current behavior
- go to https://datacube.zazukoians.org/app/projects/https:%2F%2Fdatacube.zazukoians.org%2Fproject%2F525a00f9-1c89-4a6b-83c6-f5df49ace9d7/tables
- click **preview mapped data** for the fact table
![grafik](https://user-images.githubusercontent.com/26090254/74422675-424dcf80-4e4f-11ea-8534-ef4e03158ddc.png)

## Expected behavior
working preview of mapped data

**Comment by tpluscode** [comment]
I'm on it. Turns out it's a regression caused by adding configurable csv dialect (delimiter+quote char).

It breaks because the samples are always stored with their own form, regardless of how the "real" files are structured
