### ISSUE TITLE
Unable to create a link between tables (Fact to Dimension or Dimension to Subdimension)

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/data-cube-curation#231]
## Current behavior
Each time I try to create a new link (or recreate an existing link) the program displays an error "Internal server error : "Cannot read property 'propertyTemplate' of undefined"
The browser (Firefox) must be restarted. 

It happens in the project Stapfer :
https://datacube.zazukoians.org/app/projects/https:%2F%2Fdatacube.zazukoians.org%2Fproject%2Fc9a4ea49-2fdb-44d0-b6bd-9fd33d68a631/tables

and the project Staatsrechnungen :
https://datacube.zazukoians.org/app/projects/https:%2F%2Fdatacube.zazukoians.org%2Fproject%2Fb86db429-a69e-4b49-ae9b-5444c94081d9/tables

**Comment by tpluscode** [comment]
Are you saying that the problem is solved, at least temporarily, when the browser is reloaded?

**Comment by PDumasBAR** [comment]
No each time we try to save the link the browser crash with the same error.
