### ISSUE TITLE
Unconsistent delete column in form "Create table from column"

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/data-cube-curation#235]
## Current behavior
Deleting a column when creating a new table does not delete the entire row. It seems that the Property columns stay in place.  So the Property of the deleted rows become the Property of the following row, cascading the decalage until the last row.

Sample. 
1. before delete: in yellow, the row to delete
![Del-Field-01](https://user-images.githubusercontent.com/35593772/75559196-51ce3a80-5a43-11ea-97d9-120ebc6d1dc3.PNG)

2. after the delete: in yellow, the property of the deleted row stay in place
![Del-Field-02](https://user-images.githubusercontent.com/35593772/75559202-5561c180-5a43-11ea-9e9d-b0af9b579961.PNG)

**Comment by martinmaillard** [comment]
Thanks for reporting this. I think I know why it happens. Will fix right away.
