### ISSUE TITLE
Deleting table doesn't delete references to it

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/data-cube-curation#240]
When deleting a table that was referenced by another table (link), the reference attribute is not deleted.

**Comment by tpluscode** [comment]
Should it even be allowed to remove a table which is referenced?

**Comment by martinmaillard** [comment]
Why not?

I guess we could decide that it's not allowed, but I don't see a good reason for that.

**Comment by martinmaillard** [comment]
I think this is fixed now. Is it possible? @tpluscode

**Comment by tpluscode** [comment]
Yes, it should be, with the relations being removed both ways
