### ISSUE TITLE
Pipeline fails to parse first column when CSV file starts with BOM

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/data-cube-curation#243]

**Comment by tpluscode** [comment]
See rdf-ext/rdf-parser-csvw#24

**Comment by ktk** [comment]
I had that twice meanwhile, according to the linked issue that should not happen anymore?

This happens on https://datacube.zazukoians.org/project/b86db429-a69e-4b49-ae9b-5444c94081d9 for example.

**Comment by martinmaillard** [comment]
In my experience, the `bom` option never actually fixed the issue (hence why it's still open).
