### ISSUE TITLE
When creating FactTable with invalid name, table is still assigned to project

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/data-cube-curation#257]
If I try to create a FactTable with a weird character in its name, I get a weird parsing error from the API and the table is not created. But it seems that the table is still assigned to the project. If I fix the name and re-submit the form, I get the following error: `Fact table has already been selected.`

**Comment by tpluscode** [comment]
Interesting find. Apparently the triples are create fine with non-ASCII characters in URI but than fail to read back (the parsing error is SPARQL query)
