### ISSUE TITLE
Renaming a project adds a name to it instead of replacing it

### ISSUE THREAD

**Issue by martinmaillard** [zazuko/data-cube-curation#272]
If I rename a project (in the project settings), the name ends up having multiple values (I think). It looks like `[ "The original name", "The changed name" ]`.

**Comment by tpluscode** [comment]
Oh bugger, that is interesting. Caused by an empty `WHERE` in `DELETE/INSERT`.

I was pretty sure that it was supposed to unconditionally modify the dataset. Guess not
