### ISSUE TITLE
Configuring Vue base URL

### ISSUE THREAD

**Issue by tpluscode** [zazuko/data-cube-curation#89]
[...] I noticed that the Dockerfile has [the domain name hardcoded](https://github.com/zazuko/data-cube-curation/blob/master/Dockerfile#L16). It should probably come from the environment.

_Originally posted by @martinmaillard in https://github.com/zazuko/data-cube-curation/pull/88#issuecomment-553780786_

**Comment by sandhose** [comment]
I'm writing a helm chart to deploy instances on the sbar cluster. We need a way to set this at runtime if we don't want build a docker image for each deployment
